services:
  - type: web
    name: flappy-bird-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn web_game:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGODB_URI
        fromDatabase:
          name: flappy-mongo
          property: connectionString

databases:
  - name: flappy-mongo
    databaseName: flappy_game
    plan: free
